### ISSUE TITLE
MagnaElectronics : Company logo displayed 2 times; Graph without active data; Careers and Targetare link does not work

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#380]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Type 'MagnaElectronics' in Search bar
3) Check the logo
4) Click on one logo
5) Check graph
6) Go to logo -> Click on Careers
7) Go to logo -> Click on Targetare.ro

EXPECTED RESULTS:
The 'MagnaElectronics' Company logo appears once
The graph is active, it shows the number of valid jobs in the last few days
Careers link opens correctly
Targetare link opens correctly

ACTUAL RESULTS:
The 'MagnaElectronics' Company logo appears 2 times
Graph without active data.
Careers link does not open 'MagnaElectronics' career section
Targetare link does not open targetare.ro 

![cap030](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/73f36b7a-40e6-4b5b-91cb-6a381620f835)
![cap031](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/994c865f-829c-401a-8aea-adc2446500d9)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting careers and targetare link still not working

**Comment by lalalaurentiu** [comment]
I don't see any problem!!
![Screenshot 2024-02-10 at 16 41 32 (2)](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/bf422082-5aec-40d6-b7d4-52e0da77988a)
