### ISSUE TITLE
Arabesque- Status inactive/ Missing company logo

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#542]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/arabesque/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Click on 'Run scraper' button
3. Check 'Status' section
4. Check for the logo

EXPECTED RESULTS:
Status should be Active and the company logo should be displayed

ACTUAL RESULTS:
Status is inactive and company logo is missing

![a37](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/4a34f6c6-0206-4839-9fe6-e1abe829f113)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting:  -status is activ
                          -company logo still missing on scrapers and on firme

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/1cc8b5b9-59d1-4b49-8646-8af2dbb2e72e)

**Comment by lalalaurentiu** [comment]
Fixed
![Screenshot 2024-02-15 at 02 04 15 (2)](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/a6a246eb-060d-4688-9af5-2ea1c6bd43ef)
![Screenshot 2024-02-15 at 02 04 19 (2)](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/3e969e64-1f28-4449-ab0e-67ec5b664cb0)
