### ISSUE TITLE
EUROTECH - Missing company logo

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#590]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/eurotech/index.html#)

EXPECTED RESULTS:
The company logo is visible in the square in the middle of the page.

ACTUAL RESULTS:
The company logo is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/617e951d-1272-4345-af69-87f2d4a8b477)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
The Targetare and the Careers link issues are still there.



https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/849210d3-5014-4c2a-a792-88f857503e34
